//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpencesTracker.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Profitocracy.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        internal static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new transaction.
        /// </summary>
        internal static string AddNewTransaction {
            get {
                return ResourceManager.GetString("AddNewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AddTransaction_NoneCategory {
            get {
                return ResourceManager.GetString("AddTransaction_NoneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make the changes take effect, you need to restart the application..
        /// </summary>
        internal static string ChangeLanguageAlertMessage {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ChangeLanguageAlertOk {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ChangeLanguageAlertTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be a number.
        /// </summary>
        internal static string CommonError_AmountNumber {
            get {
                return ResourceManager.GetString("CommonError_AmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance must be a number.
        /// </summary>
        internal static string CommonError_BalanceNumber {
            get {
                return ResourceManager.GetString("CommonError_BalanceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get current profile.
        /// </summary>
        internal static string CommonError_GetCurrentProfile {
            get {
                return ResourceManager.GetString("CommonError_GetCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find settings.
        /// </summary>
        internal static string CommonError_GetSettings {
            get {
                return ResourceManager.GetString("CommonError_GetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount must be a number.
        /// </summary>
        internal static string CommonError_PlannedAmountNumber {
            get {
                return ResourceManager.GetString("CommonError_PlannedAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction type.
        /// </summary>
        internal static string CommonError_TransactionType {
            get {
                return ResourceManager.GetString("CommonError_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create first profile.
        /// </summary>
        internal static string CreateFirstProfile {
            get {
                return ResourceManager.GetString("CreateFirstProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily amounts.
        /// </summary>
        internal static string DailyAmounts {
            get {
                return ResourceManager.GetString("DailyAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string DarkThemeText {
            get {
                return ResourceManager.GetString("DarkThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by date.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorAlert_Description {
            get {
                return ResourceManager.GetString("ErrorAlert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find transaction to delete.
        /// </summary>
        internal static string ErrorAlert_FindTransactionToDelete {
            get {
                return ResourceManager.GetString("ErrorAlert_FindTransactionToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get category info.
        /// </summary>
        internal static string ErrorAlert_GetCategoryInfo {
            get {
                return ResourceManager.GetString("ErrorAlert_GetCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Try again.
        /// </summary>
        internal static string ErrorAlert_InternalErrorTryAgain {
            get {
                return ResourceManager.GetString("ErrorAlert_InternalErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ErrorAlert_Ok {
            get {
                return ResourceManager.GetString("ErrorAlert_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open category adding page.
        /// </summary>
        internal static string ErrorAlert_OpenAddCategoryPage {
            get {
                return ResourceManager.GetString("ErrorAlert_OpenAddCategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open transaction adding page.
        /// </summary>
        internal static string ErrorAlert_OpenAddTransactionPage {
            get {
                return ResourceManager.GetString("ErrorAlert_OpenAddTransactionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot show filtered transactions.
        /// </summary>
        internal static string ErrorAlert_ShowFilteredTransactions {
            get {
                return ResourceManager.GetString("ErrorAlert_ShowFilteredTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorAlert_Title {
            get {
                return ResourceManager.GetString("ErrorAlert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From actual balance.
        /// </summary>
        internal static string FromActualBalance {
            get {
                return ResourceManager.GetString("FromActualBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From initial balance.
        /// </summary>
        internal static string FromInitialBalance {
            get {
                return ResourceManager.GetString("FromInitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to expenses.
        /// </summary>
        internal static string GoToExpenses {
            get {
                return ResourceManager.GetString("GoToExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance.
        /// </summary>
        internal static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string LightThemeText {
            get {
                return ResourceManager.GetString("LightThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limits.
        /// </summary>
        internal static string NoLimits {
            get {
                return ResourceManager.GetString("NoLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned amount.
        /// </summary>
        internal static string PlannedAmount {
            get {
                return ResourceManager.GetString("PlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string RussianLanguage {
            get {
                return ResourceManager.GetString("RussianLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save category.
        /// </summary>
        internal static string SaveCategory {
            get {
                return ResourceManager.GetString("SaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SavedBalance {
            get {
                return ResourceManager.GetString("SavedBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save transaction.
        /// </summary>
        internal static string SaveTransaction {
            get {
                return ResourceManager.GetString("SaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        internal static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify planned amount.
        /// </summary>
        internal static string SpecifyPlannedAmount {
            get {
                return ResourceManager.GetString("SpecifyPlannedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending types.
        /// </summary>
        internal static string SpendingTypes {
            get {
                return ResourceManager.GetString("SpendingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemThemeText {
            get {
                return ResourceManager.GetString("SystemThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no categories.
        /// </summary>
        internal static string ThereIsNoCategories {
            get {
                return ResourceManager.GetString("ThereIsNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
    }
}
